name: BUILD CICD-MINIO IMAGE

on:
  push:
    branches: [ develop ]

env:
  VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout local
        uses: actions/checkout@v4
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Fetch latest version
        run: |
          python3 .github/workflows/docker-version.py >> $GITHUB_ENV
      - 
        name: Build and export to Docker
        uses: docker/build-push-action@v5
        if: ${{ github.ref }} == 'refs/heads/develop'
        with:            
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/minio-cicd:develop
          build-args: |
            VERSION=${{ env.VERSION }}